[project]
name = "buildcheck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "reflex>=0.8.0",
    "reflex-enterprise>=0.3.0",
]
